language: haskell

before_install:
  - cabal install cabal-install
  - cabal install hakyll --flags="-checkExternal"
  - cabal install --only-dep

install:
  - cabal configure && cabal install

script:
  - cabal run build
