language: haskell

before_install:
  - cabal install cabal-install
  - cabal install hakyll --constraint="resourcet>=1.1"
  - cabal install --only-dep

install:
  - cabal configure && cabal install

script:
  - cabal run build
